name = "Simple-Blog"
license = "MIT"
licenselink = "https://github.com/sakadonohito/simple-blog/blob/master/LICENSE.md"
description = "simple theme sample"
homepage = "http://tech.k-zak.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "sakadonohito"
  homepage = "http://tech.k-zak.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
